### ISSUE TITLE
Minecraft Java Server crashes on start.

### ISSUE THREAD

**Issue by bob448** [BattlefieldDuck/WindowsGSM#149]
**Describe the bug**
Whenever I start a minecraft Java server, It crashes. But when I run it normally from windows explorer, It works.
**To Reproduce**
1. Go to Home
2. Click on Start
3. See error

**Expected behavior**
Starting the minecraft java server.
**Screenshots**
![image](https://user-images.githubusercontent.com/74561828/230104439-3cfd163d-7c33-41e4-beb1-1378c4e9fd57.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version v1.23.1

**Comment by Zudakas** [comment]
I also have this issue, I've tried reinstalling java, and setting environment variables, but nothing seems to work. Server runs fine from a batch file, but fails when trying to start from WindowsGSM. 

Console output: 

java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 

However, Java is installed correctly, and is the proper version for Minecraft 1.19.4. It loads fine when run with a simple batch file:

@ECHO OFF
java -Xms16G -jar server.jar
pause



OS: Windows 10
Browser: Edge 
Version 1.23.1

(Java version Eclipse Temuring JRE 8u362-b09)

**Comment by jframptondev** [comment]
Uninstall all vesions of java and use this instead. :)
https://www.oracle.com/java/technologies/downloads/#jdk17-windows

The one that GSM tries to install is unsupported
